spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1835
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      max-lifetime: 1800000
      initialization-fail-timeout: 0
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
  secret: 8f4a3b9c2d6e8f1a4b7c9d2e6f8a3b9c2d6e8f1a4b7c9d2e6f8a3b9c2d6e8f1a
  expiration: 3600 # 1 hour in seconds
servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
      enabled: true

